### ISSUE TITLE
Gaussian blur processor distorts image edges

### ISSUE THREAD

**Issue by Dosant** [twilio/twilio-video-processors.js#22]
- [x] I have verified that the issue occurs with the latest twilio-video-processors.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video-processors.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video-processors.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Use the code from the announcement blog post: https://www.twilio.com/blog/introducing-virtual-backgrounds-browser-based-video-applications 

You can see in the announcement that the Gaussian blur processor mixes image edges with black pixels. 
This is a minor bug, but this doesn't happen in other video conferencing apps. Edges should stay sharp. 

A screenshot from an annoncement blog post where you can see the bug:
<img width="634" alt="Screenshot 2021-07-06 at 21 27 44" src="https://user-images.githubusercontent.com/7784120/124657131-64138080-dea2-11eb-8bbb-a4a45347b462.png">

**Expected behavior:**

Edges should stay sharp when blurring the background

**Actual behavior:**

Edges are blurred and mixed with black pixels 

**Software versions:**

 - [x] twilio-video-processors.js: 1.0.0

**Comment by charliesantos** [comment]
Thanks @Dosant for submitting! This should get addressed once we switch to a WebGL pipeline. However, this is currently low in priority.

**Comment by Dosant** [comment]
> This should get addressed once we switch to a WebGL pipeline. However, this is currently low in priority.

Hmm 🤔 Sorry, but not following the relation to the WebGL pipeline.

I think the current approach should work if you'd compose 3 layers as follows?

```
ctx.draw(originalImage) // 1st layer -> the original image
ctx.draw(blurredImage) // 2nd layer -> blurred image so we get blurred background and edge nicely overlaps with the background from original image (it likely needs a `globalCompositeOperation` ctx setting tweak here, not sure)
ctx.draw(personMask)
```

**Comment by charliesantos** [comment]
> > This should get addressed once we switch to a WebGL pipeline. However, this is currently low in priority.
> 
> Hmm 🤔 Sorry, but not following the relation to the WebGL pipeline.
> 
> I think the current approach should work if you'd compose 3 layers as follows?
> 
> ```
> ctx.draw(originalImage) // 1st layer -> the original image
> ctx.draw(blurredImage) // 2nd layer -> blurred image so we get blurred background and edge nicely overlaps with the background from original image (it likely needs a `globalCompositeOperation` ctx setting tweak here, not sure)
> ctx.draw(personMask)
> ```

We are planning to make some improvements using WebGL, which will include the fix for this issue. However, low priority for now.

Regarding your approach, I think it's a good one for the short term. I'll submit an internal ticket and we'll consider including it in the next release, as long as it doesn't add significant GPU/CPU usage. Thank you for sharing!

**Comment by vbabenko** [comment]
I have the same problem
- twilio-video-processors.js: 1.0.2

**Comment by charliesantos** [comment]
Hey folks, I'm closing this one out since it's the default behavior of the blur filter of the browser. I submitted an internal ticket as an "enhancement" which should get addressed once we switch to WebGL. But feel free to follow up in this space. Thanks!
