### ISSUE TITLE
Adding a video processor makes my video disappear

### ISSUE THREAD

**Issue by nickjgentile** [twilio/twilio-video-processors.js#24]
Some details about the env/package versions I am working with:

Node v14.17.0
Twilio-Video package v2.15.1 (downloaded via npm)
@twilio/video-processors v.1.0.1 (downloaded via npm)
NPM v6.14.13

Hi, I have an application that I use twilio-video for to allow users to conference with one another, and im trying to prototype out the use of video backgrounds, however I am finding that any time I add a processor to a video track, it just dispapears, if I call `removeProcessor` on that track, it instantly starts working again. So I assume I am not doing something right with my processor. 

Here is the block where I am creating the processor (the ai model seems to load fine, and nothing errors out, seems to construct the processor without issues)

`     let virtualBackground
      const img = new Image()
      img.src = 'https://www.adweek.com/wp-content/uploads/2020/03/behr-zoom-background-feature-2020-600x315.jpg'

      img.onload = async () => {
        virtualBackground = new VirtualBackgroundProcessor({
          assetsPath: '',
          backgroundImage: img
        })

        await virtualBackground.loadModel()`
        
 I am then just setting the virtualBackground var on the window as well as the track I am rendering for testing purposes.
 
 After getting the processor and track on the window object, I just connect to a conference with my track, which works fine and the video is there. After running `window.track.addProcessor(window.virtualBackground)` however, the video just disappears whereas I would expect it to just remove the background as it does in this repo's example. As soon as I run `window.track.removeProcessor(window.virtualBackground)` the video appears again, so the processor seems to just be causing issues.
 
 One thing worth possibly noting is that I am getting my tracks a little bit different than in the example, but still am using the twilio-video sdk to do so: `var preSetTracks = await Video.createLocalTracks(localTracksConfig)`
 
 I am attaching a screenshot of what is returned when I run `window.track.addProcessor(window.virtualBackground)` also, I see that there is a processedTrack property on it.
<img width="1377" alt="Screen Shot 2021-07-14 at 11 22 43 AM" src="https://user-images.githubusercontent.com/28357364/125657470-5d268aea-f92d-45d6-87f6-a0b216633a54.png">

**Comment by charliesantos** [comment]
Hey @nickjgentile , thanks for submitting! Can you please provide a room sid, console logs, and a code snippet the shows the following?

- create video track
- joining to a room with the created track
- initializing the video processor
- adding the video processor
- removing the video processor

**Comment by nickjgentile** [comment]
@charliesantos sure! Here is a room sid I recently was working in: `RM6fb9fd7f44362dd4fd28ae4024b32fe1` 

I'll attach larger snippets of the code:

The snippet below is a method that takes a track and adds a processor to it:

`  setVideoBackground(track) {
    if (!isSupported) {
      console.warn('Video backgrounds only supported with Chromium based browsers')
    }
    return new Promise((resolve, reject) => {
      let virtualBackground
      const img = new Image()
      img.src =
        'https://www.adweek.com/wp-content/uploads/2020/03/behr-zoom-background-feature-2020-600x315.jpg'

      img.onload = async () => {
        virtualBackground = new VirtualBackgroundProcessor({
          assetsPath: '',
          backgroundImage: img
        })

        await virtualBackground.loadModel()
        window.virtualBackground = virtualBackground
        track.addProcessor(virtualBackground)
        return resolve(track)

        // createLocalVideoTrack({
        //   height: 360,
        //   width: 640,
        //   aspectRatio: 1.777777778,
        //   frameRate: 24
        // }).then(track => {
        //   track.addProcessor(virtualBackground)
        //   return resolve(track)
        // })
      }
    })
  }`
  
  This next snippet, which is rather large, includes my logic for creating the tracks, I then take the video track and sent it to the method above ^^ to add a processor to the track. With my preset tracks, I am connecting to a room:
  
 `  async connectToRoom(data) {
    var recordConference = !!(data && data.recordConference)
    var recordScreen = !!(data && data.recordScreen)
    if (recordScreen) {
      try {
        this.screenRecordingStream = await navigator.mediaDevices.getDisplayMedia({
          audio: false,
          video: {
            frameRate: 30,
            height: 1080,
            width: 1920
          }
        })
      } catch (err) {
        Eventbus.$emit('screen-recording-selection-cancelled', {})
        return
      }
    }

    let token = await this.getAccessToken(data.roomId, data.socketId, recordConference)

    let localTracksConfig = {}

    if (data.videoInputDeviceFound) {
      localTracksConfig.video = {
        deviceId: data.videoInput || 'default',
        height: 360,
        width: 640,
        aspectRatio: 1.777777778
      }
    }

    if (data.audioInputDeviceFound) {
      localTracksConfig.audio = {
        deviceId: data.audioInput || 'default'
      }
    }

    MediaDeviceManager.setAudioOutput(data.audioOutput)

    var preSetTracks = await Video.createLocalTracks(localTracksConfig)

    var preSetVideoTrack = preSetTracks.find(track => track.kind == 'video')
    window.videoTrack = preSetVideoTrack
    await this.setVideoBackground(preSetVideoTrack)

    if (data && data.videoHidden && data.videoInputDeviceFound) {
      var videoTrack = preSetTracks.find(track => track.kind == 'video')
      videoTrack.mediaStreamTrack.stop()
      videoTrack.mediaStreamTrack.enabled = false
    }

    if (data && data.micMuted && data.audioInputDeviceFound) {
      var audioTrack = preSetTracks.find(track => track.kind == 'audio')
      audioTrack.mediaStreamTrack.enabled = false
    }

    var room = await Video.connect(token, {
      name: data.roomName || uuid(),
      dominantSpeaker: true,
      tracks: preSetTracks,
      bandwidthProfile: {
        video: {
          mode: 'collaboration',
          trackSwitchOffMode: 'detected',
          maxSubscriptionBitrate: 2400000,
          dominantSpeakerPriority: 'standard',
          maxTracks: 25, // default logic = activity, when a track stops there is a track switchoff event to queue off of
          renderDimensions: {
            high: {
              width: 1920,
              height: 1080,
              framerate: 10
            },
            standard: {
              width: 640,
              height: 360
            },
            low: {
              width: 640,
              height: 360
            }
          }
        }
      },
      maxAudioBitrate: 16000,
      preferredVideoCodecs: [
        {
          codec: 'VP8',
          simulcast: true
        }
      ]
    })
    window.twilioRoom = room

    if (recordScreen && this.screenRecordingStream) {
      await this.publishLocalScreenshareTrackForRecording(this.screenRecordingStream)
    }

    this.initializeRoom(room, preSetTracks)

    var conferenceParticipants = conferenceParticipantsUtil.getConferenceParticipantsFromTwilioRoomParticipants(
      room.participants
    )
    var localParticipant = conferenceParticipantsUtil.getConferenceParticipantFromTwilioRoomParticipant(
      room.localParticipant
    )

    room.localParticipant.tracks.forEach(track => {
      if (
        track.track &&
        (!track.trackName || track.trackName !== 'screenRecording') &&
        (track.kind == 'audio' || track.kind == 'video')
      ) {
        localParticipant.trackElements[track.kind] = track.track.attach()
      }
    })

    return {
      participants: conferenceParticipants,
      localParticipant,
      conferenceBeingRecorded: window && window.twilioRoom && window.twilioRoom.isRecording,
      preSetTracks,
      screenRecordingStream: this.screenRecordingStream || null
    }
  }`
  
  You may notice that along the way with this logic I am just setting the processor that I generate to a var on the window, and the video track that i generate to a var on the window as well. I am testing turning the processor on and off for the track by just calling `window.videoTrack.removeProcessor(window.virtualBackground)` and `window.videoTrack.addProcessor(window.virtualBackground)` in the console for my browser to see what happens when I turn it on and off.

**Comment by charliesantos** [comment]
Thanks @nickjgentile for the detailed information. I will take a look later to try and understand more what your code is trying to do. Meanwhile, on your image source https://www.adweek.com/wp-content/uploads/2020/03/behr-zoom-background-feature-2020-600x315.jpg, I'm assuming this is not served in the same domain as your web app correct? You might run into CORS issues, which silently fails when drawn in the canvas. Please read the details in our documentation about source images here https://twilio.github.io/twilio-video-processors.js/interfaces/virtualbackgroundprocessoroptions.html#backgroundimage

There are two things you can try:
1) Serve the image in the same folder where you are serving your js, css, and html files and/or
2) Set the image crossOrigin attribute
```js
img.crossOrigin = 'anonymous';
```

**Comment by nickjgentile** [comment]
@charliesantos that did it, greatly appreciate your help!
