### ISSUE TITLE
Safari Crashes the Twilio Video React App

### ISSUE THREAD

**Issue by cfluke-twilio** [twilio/twilio-video-processors.js#25]
I updated the Twilio Video React App with the new .5 update and the app now crashes when joining a video room.

 - [x] I have verified that the issue occurs with the latest twilio-video-processors.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video-processors.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video-processors.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Console stack that is relevant
```
ReferenceError: Can't find variable: OffscreenCanvas
t — BackgroundProcessor.ts:160
t — GaussianBlurBackgroundProcessor.ts:58
(anonymous function) — useBackgroundSettings.ts:83
```

Safari doesn't seem to have OffscreenCanvas yet

**Expected behavior:**

Join Room

**Actual behavior:**

White Screen

**Software versions:**

 - [ ] Browser(s): Safari
 - [ ] Operating System: Mac and IOS
 - [ ] twilio-video-processors.js: 1.0.1
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by charliesantos** [comment]
@cfluke-twilio thanks for reporting. Are you referring to this react app? https://github.com/twilio/twilio-video-app-react

**Comment by cfluke-twilio** [comment]
Yes. sorry.

**Comment by charliesantos** [comment]
@cfluke-twilio no worries. We just released the latest version of react app. Have you tried on master branch (version 0.5.0 August 9, 2021)? We added `isSupported` checks to prevent this crash.

**Comment by charliesantos** [comment]
Just talked to @cfluke-twilio internally and this was a caching issue on his side. Closing.
