### ISSUE TITLE
Avoid to load model multiple times

### ISSUE THREAD

**Issue by Takeno** [twilio/twilio-video-processors.js#26]
Currently, everytime you call `AnyProcessor.loadModel()` it makes 3 ajax calls to load assets, even if they are already loaded.

Before opening a PR, I would like to discuss with you if it can be useful to avoid to load models multiple times for the same configuration. 

The idea is to changes this: [processors/background/BackgroundProcessor.ts#L105](https://github.com/twilio/twilio-video-processors.js/blob/master/lib/processors/background/BackgroundProcessor.ts#L105) with a sort of memoization based on config.

The expected result is more efficient activation of the processor after the first time.

**Comment by manjeshbhargav** [comment]
Hi @Takeno ,

Thanks for writing in with this question. We have a plan to work on this as part of a future release. Please watch this space for updates.

**Comment by vbabenko** [comment]
Hi there,
Any updates here?

**Comment by manjeshbhargav** [comment]
Hi @vbabenko ,

We are planning to take this up at the beginning of next year. Please watch this space for updates.

**Comment by charliesantos** [comment]
We fixed this and it's scheduled to release soon. Please watch this space for updates.
