### ISSUE TITLE
Browser Crash with Video Processor

### ISSUE THREAD

**Issue by moretalk** [twilio/twilio-video-processors.js#27]
- [X] I have verified that the issue occurs with the latest twilio-video-processors.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video-processors.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video-processors.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```ts
      const img = new Image();
      img.setAttribute("crossOrigin", "anonymous");
      img.crossOrigin = "anonymous";
      img.onload = () => {
        const virtualBackground = new VirtualBackgroundProcessor({
          assetsPath: 'https://cdn.ciptex.com/race-video/tflite',
          backgroundImage: img,
        });

        virtualBackground.loadModel().then(() => {
          let localVideo = track.attach();
           if (track.processor) {
                track.removeProcessor(track.processor);
           }
           track.addProcessor(virtualBackground);
           localVideo.style.maxWidth = "100%";
           room.localParticipant.publishTrack(track);
           document.getElementById("local-media").appendChild(localVideo);
        });
      };
      img.src = backgroundURL; //Chosen Image File
```

**Expected behavior:**

Video with Virtual Background

**Actual behavior:**

Chrome Tab Completely Locked and Crashed. No Console Logs Present

Commenting out track.addProcessor(virtualBackground); stops the crash and video works successfully without Virtual Background

**Software versions:**

 - [x] Browser(s): Google Chrome
 - [X] Operating System: macOS Big Sur 11.4
 - [X] twilio-video-processors.js: 1.0.1
 - [X] twilio-video: 2.16.0
 - [X] Third-party libraries (e.g., Angular, React, etc.): React 16.5.2 (Twilio Flex)

**Comment by moretalk** [comment]
Just an Update on this. 

It seems to be specific to Version 92.0.4515.159 (Official Build) (x86_64) of Google Chrome which requires a clear of Local Storage and Cookies after browser upgrade. Once I had cleared Local Storage and Cookies I no longer experienced the crash.

Other users in our team already on 92.0.4515.159 who had NOT used Video Processors did not experience the crashing.

**Comment by manjeshbhargav** [comment]
Hi @moretalk ,

Thanks for reporting this issue. Can you try this with Chrome Beta (v93) to see if it is happening there as well?

**Comment by KaelWD** [comment]
I'm also seeing this in chrome 92.0.4515.159 if I log a LocalVideoTrack with processor attached through [`consola`](https://www.npmjs.com/package/consola), or if I try to view a Vue component that has tracks with processors in its data in vue-devtools.

**Comment by BlackNightFury** [comment]
Hi, Everyone. I am also experiencing this kinda crashing and it is making us not to use `GaussianBlurBackground` feature anymore. It is crashing browser tap as always and I can see that CPU usage is over 100% at that time. Do we have any fix, workaround for this?

**Comment by KaelWD** [comment]
This worked for me:
```js
const processor = new GaussianBlurBackgroundProcessor()
await processor.loadModel()
// Prevent unwanted iteration over large arrays
;['_tflite', '_currentMask', '_dummyImageData', '_masks'].forEach(key => {
  Object.defineProperty(processor, key, {
    configurable: true,
    enumerable: false,
    value: processor[key],
    writable: true,
  })
})
video.addProcessor(processor)
```

**Comment by BlackNightFury** [comment]
@KaelWD I really can't know how to thank you. But it is working perfectly!!!!!. Thanks for your help

**Comment by charliesantos** [comment]
Hey everyone, thank you for the report and the workaround. I believe the browser is crashing when you try to stringify the video processor object correct? Though we don't recommend stringifying the whole object, you can do what @KaelWD 's solution if you really have to do it.

I will close this issue now since there's no action item on our side.

**Comment by moretalk** [comment]
> 

Sorry but where am I trying to stringify the video processor object in my original code?
