### ISSUE TITLE
Unhandled Rejection (TypeError): window.createTwilioTFLiteModule is not a function

### ISSUE THREAD

**Issue by bhavinatharva** [twilio/twilio-video-processors.js#39]
![image](https://user-images.githubusercontent.com/84075780/146010287-dc25d355-e207-40c0-8fb2-f86c7e246168.png)

 - [x] I have verified that the issue occurs with the latest twilio-video-processors.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video-processors.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video-processors.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
blurBackground.loadModel().then(() => {
        createLocalVideoTrack({
          width: 640,
          height: 480,
          frameRate: 24
        }).then(track => {
          window.track.addProcessor(blurBackground);
        });
      });

```ts
// TODO
```

**Expected behavior:**
  it should load video with blur background
TODO

**Actual behavior:**
Gives an error of undefined function
TODO

**Software versions:**

 - [ ] Browser(s): Version 96.0.4664.110 (Official Build) (64-bit)
 - [ ] Operating System: Ubuntu 18
 - [ ] twilio-video-processors.js: 1.0.2
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by charliesantos** [comment]
@bhavinatharva it seems like the library is not finding the `tflite-simd-1-0-0.js` or `tflite-1-0-0.js`.
- please make sure you followed the [instructions](https://github.com/twilio/twilio-video-processors.js#assets) for serving the assets files
- please post a screenshot of the requests to the tflite JS files by opening your chrome debugger network tab. Please let me know the response of each request

**Comment by bhavinatharva** [comment]
HI @charliesantos Thanks for the reply
![image](https://user-images.githubusercontent.com/84075780/146139467-57f08b3e-b752-433f-ba4b-438f150bd89b.png)

**Comment by bhavinatharva** [comment]
@charliesantos 
![image](https://user-images.githubusercontent.com/84075780/146139677-6a2312f3-c56d-440a-af41-20fec7b0696e.png)

i am getting this in console
![image](https://user-images.githubusercontent.com/84075780/146139850-46eb0ade-292e-466c-8967-e258cdcb4f4e.png)

even though my browser is perfectly supported

**Comment by bhavinatharva** [comment]
@charliesantos, Need to put all asset files in public folder and give the assetpath: '/' resolve the issue

**Comment by AndreyPatseiko** [comment]
I used this approach in React js app https://giters.com/twilio/twilio-video-processors.js/issues/38
