### ISSUE TITLE
use TFJS instead of TFLite

### ISSUE THREAD

**Issue by trickpattyFH20** [twilio/twilio-video-processors.js#43]
**What is the feature that you would like to see? Please describe.**
Use the TFJS BodyPix model rather than the TFLite "MediaPipe Selfie Segmentation Landscape Model."
TFJS Bodypix works in both Firefox and Chrome since it does not require Webassembly.
https://github.com/tensorflow/tfjs-models/tree/master/body-pix

**Is your feature request related to a problem? Please describe.** 
Yes. Twilio video processors do not work outside of Chrome.

**Describe alternatives you've considered**
Integrate TFJS BodyPix in a Twilio Video project outside of the Twilio Video Processors library.

**Additional context**
I like Firefox.

**Comment by trickpattyFH20** [comment]
Could it be done with a regular canvas that is hidden and exists in the dom? @alex-konoval

**Comment by alex-konoval** [comment]
@trickpattyFH20  As I know `OffscreenCanvas` is used for performance reasons.

**Comment by charliesantos** [comment]
Hey everyone, thanks for submitting this ticket. We did not use tfjs and bodypix due to performance reasons - FPS and accuracy are significantly lower. Having said that, we are working on supporting other browser such as firefox and safari. Please continue to watch out for future releases.
