### ISSUE TITLE
Remote video track not working with VirtualBackgroundProcessor

### ISSUE THREAD

**Issue by Kstar0722** [twilio/twilio-video-processors.js#44]
It works VirtualBackgroundProcessor in local track, but I see blank screen in the remote track with VirtualBackgroundProcessor
I checked remote video track object. and there's no processor(processor: undefined)

 - [x] I have verified that the issue occurs with the latest twilio-video-processors.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video-processors.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video-processors.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Does not showing remote video track with background

**Actual behavior:**

Need to show remote video track with background

**Software versions:**

 - [x] Browser(s): Chrome 103.0.5060.114 (Official Build) (arm64)
 - [x] Operating System: macOS Monterey
 - [x] twilio-video-processors.js:  1.0.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by charliesantos** [comment]
Hey @Kstar0722 can you please provide steps to reproduce, code snippet on how you're adding the processor, and also a room sid?

**Comment by charliesantos** [comment]
Hi @Kstar0722 , adding background after publishing track should work. Can you please provide a code snippet on how you're adding the background? That is, please show `this.addBackgroundToVideoTrack(track, args.backgroundUrl)` implementation. Also, are you getting any log messages? Can you please enable debug mode on twilio-video and provide logs?

**Comment by charliesantos** [comment]
@Kstar0722 thank you for providing the code snippet. Nothing stands out to me so far. I have a couple of requests
1. Can you please enable debug mode on twilio-video and provide logs?
2. Please refactor your code in a way that you should initialize the video processors first so you can reuse them on demand later, especially if you have to toggle video on/off. Something like the following below. This is also the same pattern we implemented in our [demo react app](https://github.com/twilio/twilio-video-app-react) which works really great.

```ts
// Save this in your hooks or app state, or wherever your video track can access them
let blurProcessor;
let virtualBackgroundProcessor;

// Call this on your app start up
async function initializeVideoProcessors() {
  blurProcessor = new GaussianBlurBackgroundProcessor({...});
  virtualBackgroundProcessor = new VirtualBackgroundProcessor({...});
  await blurProcessor.loadModel();
  await virtualBackgroundProcessor.loadModel();
}
```

Now your `addBackgroundToVideoTrack` can be simpler
```ts
async function addBackgroundToVideoTrack(track, backgroundUrl) {
  try {
    const backgroundImage = await loadImage(backgroundUrl);
    virtualBackgroundProcessor.backgroundImage = backgroundImage;
    track.addProcessor(virtualBackgroundProcessor);
  } catch {
    track.addProcessor(blurProcessor);
  }
}

async function loadImage(url) {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = reject;
    image.src = url;
  });
}
```

**Comment by Kstar0722** [comment]
Thanks @charliesantos ,
I will try to update my code like above.

**Comment by Kstar0722** [comment]
Hi @charliesantos 
I try to update my code like your solution. but it's not working.

**Comment by charliesantos** [comment]
Can you please enable debug mode on twilio-video and provide logs?
Can you also push up your changes to a repo so I can take a look?

**Comment by Kstar0722** [comment]
ok, I will try to enable debug mode and give you callSid, maybe tomorrow morning
but I can't share my code since it's private.

**Comment by Kstar0722** [comment]
@charliesantos I checked it and seems the problem is on our end. I will close the ticket since there's no issue in this lib. thanks for your help.

**Comment by charliesantos** [comment]
@Kstar0722 I'm glad this is now resolved. What was the issue you found? It might help others in case they run into a similar issue.
