### ISSUE TITLE
Could you add Google's Selfie model

### ISSUE THREAD

**Issue by vbabenko** [twilio/twilio-video-processors.js#48]
**What is the feature that you would like to see? Please describe.**
There is a model published by Google and the quality and performance of that model are quite impressive. It has better segmentation
Link: https://google.github.io/mediapipe/solutions/selfie_segmentation.html

**Is your feature request related to a problem? Please describe.**
The existing model provided by Twilio has some artifacts around the person

**Comment by charliesantos** [comment]
Hey @vbabenko thanks for the ping. We are already using this model. The [model card](https://drive.google.com/file/d/1dCfozqknMa068vVsO2j_1FgZkW_e3VWv/preview) is link in our readme if you want to see the details.

Also, we are working on improving the accuracy and performance of the library. Please watch out for future releases in this repo.
