### ISSUE TITLE
Would it be possible to release 2.0.0-rc1 to npm?

### ISSUE THREAD

**Issue by lukewarlow** [twilio/twilio-video-processors.js#51]
Would it be possible to release 2.0.0-rc1 to npm? Cross browser support for virtual backgrounds would be very useful.

**Comment by paule-refero** [comment]
Yes, I agree it would be helpful - as our clients are looking to use both virtual and blurring backgrounds...

**Comment by genevpd** [comment]
We have Would be great if Twilio team could get back to this as we g  nice as it appears some good progress was made on https://github.com/twilio/twilio-video.js/issues/1920 

@manjeshbhargav @charliesantos just tagging you as we are not sure if this repository is still maintained by Twilio.
